/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Box;
import javax.swing.TransferHandler;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Component;

/**
 *
 * @author Xavier
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Partida partida;
    private Casilla[][] matrizCasillas = new Casilla[25][25];
    private Componente componenteSeleccionado;
    private ArrayList<Componente> todasDefensas = new ArrayList<>();
    private ArrayList<IAtacar> atacantes = new ArrayList();
    private ArrayList<Componente> todos = new ArrayList();
    private ArrayList<Componente> defensasDisponibles = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    
    /**
     * Creates new form VentanaPrincipal
     * @param partida
     */
    public VentanaPrincipal(Partida partida) {
        this.partida = partida;
        initComponents();
        inicializarTablero();
        getContentPane().setBackground(Color.blue);
        defensasTotales();
    JPanel panelDefensas = new JPanel();
    panelDefensas.setLayout(new BoxLayout(panelDefensas, BoxLayout.Y_AXIS));
    panelDefensas.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
    panelDefensas.setBackground(Color.WHITE);

    jScrollPane1.setViewportView(panelDefensas);

        actualizarScrollDefensas(panelDefensas);
    }
    
    private void defensasTotales(){
            todasDefensas.add(new ArmaAerea(1,""));
            todasDefensas.add(new ArmaAtaqueMultiple(2,""));
            todasDefensas.add(new ArmaBloque(3,""));
            todasDefensas.add(new ArmaContacto(4,""));
            todasDefensas.add(new ArmaImpacto(5,""));
            todasDefensas.add(new ArmaMedianoAlcance(6,""));
            todasDefensas.add(new ReliquiaVida("Vida","",1,1,1,7));
            for (int i = 0; i < todasDefensas.size(); i++) {
                Componente d = todasDefensas.get(i);
            if (d.getNivelDeAparicion() <= partida.getNivel()) {
                defensasDisponibles.add(d);
    }
    }
    }

    public void actualizarScrollDefensas(JPanel panelDefensas) {
        panelDefensas.removeAll(); 

        for (int i = 0; i < defensasDisponibles.size(); i++) {
            Componente d = defensasDisponibles.get(i);

            JLabel label = new JLabel(d.getNombre());
            label.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            label.setOpaque(true);
            label.setBackground(Color.LIGHT_GRAY);
            label.setMaximumSize(new Dimension(180, 30));
            label.setAlignmentX(Component.CENTER_ALIGNMENT);

            label.setTransferHandler(new TransferHandler("text"));

            panelDefensas.add(Box.createRigidArea(new Dimension(0, 5)));
            panelDefensas.add(label);
    }

        panelDefensas.revalidate();
        panelDefensas.repaint();
}
    
    private void inicializarTablero() {
    pnlTablero.removeAll();
    pnlTablero.setLayout(new GridLayout(25, 25));

    for (int i = 0; i < 25; i++) {
        for (int j = 0; j < 25; j++) {
            Casilla casilla = new Casilla(i, j);
            matrizCasillas[i][j] = casilla;

            casilla.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (componenteSeleccionado != null && casilla.estaVacia()) {
                        componenteSeleccionado.colocarEn(casilla.getXPos(), casilla.getYPos());
                        casilla.colocarComponente(componenteSeleccionado);
                        componenteSeleccionado = null;
                    }
                }
            });

            pnlTablero.add(casilla);
        }
    }

    pnlTablero.revalidate();
    pnlTablero.repaint();
}

    
    public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
        Partida partida = new Partida(); // Puedes pasar una lista vacía o zombies iniciales
        VentanaPrincipal ventana = new VentanaPrincipal(partida);
        ventana.setVisible(true);
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablero = new javax.swing.JPanel();
        pnlObjetos = new javax.swing.JPanel();
        btnNivel = new javax.swing.JButton();
        btnComenzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        pnlTablero.setBackground(new java.awt.Color(153, 153, 255));
        pnlTablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlTablero.setPreferredSize(new java.awt.Dimension(600, 600));
        pnlTablero.setLayout(new java.awt.GridLayout(25, 25));

        pnlObjetos.setBackground(new java.awt.Color(102, 153, 255));
        pnlObjetos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlObjetos.setPreferredSize(new java.awt.Dimension(294, 600));

        btnNivel.setText("-->");
        btnNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNivelMouseClicked(evt);
            }
        });

        btnComenzar.setText("Comenzar");

        jLabel1.setText("Ejército:");

        jLabel2.setText("Nivel:");

        javax.swing.GroupLayout pnlObjetosLayout = new javax.swing.GroupLayout(pnlObjetos);
        pnlObjetos.setLayout(pnlObjetosLayout);
        pnlObjetosLayout.setHorizontalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComenzar)
                .addContainerGap())
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(pnlObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43))))
        );
        pnlObjetosLayout.setVerticalGroup(
            pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObjetosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComenzar)
                    .addComponent(btnNivel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNivelMouseClicked
        partida.subirNivel();
        System.out.println(partida.getNivel());
    }//GEN-LAST:event_btnNivelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlObjetos;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
